# Notebook to retrieve the dataset

In [1]:
# read in dataset

# query images and save one by one, have a counter to keep count of the ids of images

# if image cannot be extracted, change the flag of the df to false

# at the end of all images being downloaded, filter for all positive flags

# rename the ids from initial counter value to last counter value

In [46]:
import pandas as pd
from utils.image_retrieval import read_images
import os
import re

In [2]:
df = pd.read_csv("select-first-3000-train-rows.csv")

In [3]:
df

,uid,url,key,status,original_caption,vlm_model,vlm_caption,toxicity,severe_toxicity,obscene,...,width,height,original_width,original_height,exif,sha256,image_id,author,subreddit,score
0,0065a9b1cb4da4696f2cd6640e00304257cafd97c0064d...,https://media.gettyimages.com/photos/plate-of-...,7740026,success,A plate of food from Murray Bros Caddy Shack a...,gemini-pro-vision,This image displays: A plate of fried calamar...,0.000556,0.000002,0.000038,...,612,408,612,408,"{""Image ImageDescription"": ""A plate of food fr...",0065a9b1cb4da4696f2cd6640e00304257cafd97c0064d...,NaN,NaN,-1,-1
1,c9d31cce99482e8da13f6a868e2472c3bc3ea05a874e5b...,https://thumbs.dreamstime.com/b/car-riding-wet...,7740001,success,Car riding on wet street. Car driving on wet c...,gemini-pro-vision,This image displays:\n\nA black car driving t...,0.005905,0.000017,0.000158,...,800,534,800,534,{},c9d31cce99482e8da13f6a868e2472c3bc3ea05a874e5b...,NaN,NaN,-1,-1
2,f3a6ad643814199a98f872229758b8e735773c1803e2f1...,https://images.pexels.com/photos/770224/pexels...,7740009,success,Water Coming Out Of A Pipe,gemini-pro-vision,This image displays: A large rusty pipe with ...,0.002487,0.000007,0.000093,...,500,750,500,750,{},f3a6ad643814199a98f872229758b8e735773c1803e2f1...,NaN,NaN,-1,-1
3,3b03f5e3a32499281dbeebb9a0e1d3dfe883bc7b72e2eb...,https://filmfare.wwmindia.com/content/2017/jul...,7740010,success,MARCH 2009 ''It's sad that a boy and girl can ...,gemini-pro-vision,This image displays: three pictures of Katrin...,0.001743,0.000003,0.000071,...,600,450,600,450,{},3b03f5e3a32499281dbeebb9a0e1d3dfe883bc7b72e2eb...,NaN,NaN,-1,-1
4,9f3b5395744728e68b85083c0411c3b4139214f1258bf7...,https://southernersays.com/wp-content/uploads/...,7740000,success,Humpback Whale tail in the Bay of Banderas,gemini-pro-vision,This image displays:\nA photograph of a whale...,0.006152,0.000024,0.000188,...,1024,662,1024,662,{},9f3b5395744728e68b85083c0411c3b4139214f1258bf7...,NaN,NaN,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,31844d73075701266791addc2e81f60bf5642f5f4db4ea...,https://pix.avax.news/avaxnews/7c/87/0001877c_...,7744087,success,"CGAP Photo Contest -- Maize Grinding, Uganda. ...",gemini-pro-vision,This image displays: a young boy using a mach...,0.008850,0.000026,0.000368,...,639,424,639,424,{},31844d73075701266791addc2e81f60bf5642f5f4db4ea...,NaN,NaN,-1,-1
2996,a5828cacf3ec796a6a23dce3237ff3a8691d3efaecd336...,https://candidegardening.com/img/c8aa3b54-ee4a...,7744094,success,A close up of an Alocasia amazonica plant,gemini-pro-vision,This image displays:\n\nAn Alocasia Zebrina p...,0.002838,0.000007,0.000090,...,648,519,648,519,{},a5828cacf3ec796a6a23dce3237ff3a8691d3efaecd336...,NaN,NaN,-1,-1
2997,b15b5511e33564445fa48dce5efd8b488cab721f5f2981...,https://blueridgemountainlife.com/wp-content/u...,7744110,success,Mehaffey Tree Farm after a snow.,gemini-pro-vision,This image displays:\n\nThis image displays s...,0.000460,0.000001,0.000030,...,640,427,640,427,"{""Image Make"": ""Canon"", ""Image Model"": ""Canon ...",b15b5511e33564445fa48dce5efd8b488cab721f5f2981...,NaN,NaN,-1,-1
2998,465dd7a390bea7022cdf287f08923fcde168b18054971b...,https://www.littledayout.com/wp-content/upload...,7744051,success,Go-karting In Singapore: Off To The Races,gemini-pro-vision,This image displays:\n\nThis image displays a...,0.010650,0.000063,0.000333,...,670,415,670,415,{},465dd7a390bea7022cdf287f08923fcde168b18054971b...,NaN,NaN,-1,-1
2999,6a7dd766abc71e8233d36f3ba1b0af620dd9b225108213...,https://cdn0.weddingwire.com/reviews/photos/3/...,7744098,success,The wedding of <PERSON> and Charlie Kaine Phot...,gemini-pro-vision,This image displays: A married couple is sitt...,0.006744,0.000016,0.000182,...,720,540,720,540,{},6a7dd766abc71e8233d36f3ba1b0af620dd9b225108213...,NaN,NaN,-1,-1

In [4]:
filtered_df = df.loc[:, ["url", "original_caption", "vlm_caption"]]

In [5]:
filtered_df.loc[:, "is_downloaded"] = True
filtered_df

,url,original_caption,vlm_caption,is_downloaded
0,https://media.gettyimages.com/photos/plate-of-...,A plate of food from Murray Bros Caddy Shack a...,This image displays: A plate of fried calamar...,True
1,https://thumbs.dreamstime.com/b/car-riding-wet...,Car riding on wet street. Car driving on wet c...,This image displays:\n\nA black car driving t...,True
2,https://images.pexels.com/photos/770224/pexels...,Water Coming Out Of A Pipe,This image displays: A large rusty pipe with ...,True
3,https://filmfare.wwmindia.com/content/2017/jul...,MARCH 2009 ''It's sad that a boy and girl can ...,This image displays: three pictures of Katrin...,True
4,https://southernersays.com/wp-content/uploads/...,Humpback Whale tail in the Bay of Banderas,This image displays:\nA photograph of a whale...,True
...,...,...,...,...
2995,https://pix.avax.news/avaxnews/7c/87/0001877c_...,"CGAP Photo Contest -- Maize Grinding, Uganda. ...",This image displays: a young boy using a mach...,True
2996,https://candidegardening.com/img/c8aa3b54-ee4a...,A close up of an Alocasia amazonica plant,This image displays:\n\nAn Alocasia Zebrina p...,True
2997,https://blueridgemountainlife.com/wp-content/u...,Mehaffey Tree Farm after a snow.,This image displays:\n\nThis image displays s...,True
2998,https://www.littledayout.com/wp-content/upload...,Go-karting In Singapore: Off To The Races,This image displays:\n\nThis image displays a...,True
2999,https://cdn0.weddingwire.com/reviews/photos/3/...,The wedding of <PERSON> and Charlie Kaine Phot...,This image displays: A married couple is sitt...,True

In [6]:
filtered_df["id"] = range(1, len(filtered_df)+1)

In [7]:
filtered_df

,url,original_caption,vlm_caption,is_downloaded,id
0,https://media.gettyimages.com/photos/plate-of-...,A plate of food from Murray Bros Caddy Shack a...,This image displays: A plate of fried calamar...,True,1
1,https://thumbs.dreamstime.com/b/car-riding-wet...,Car riding on wet street. Car driving on wet c...,This image displays:\n\nA black car driving t...,True,2
2,https://images.pexels.com/photos/770224/pexels...,Water Coming Out Of A Pipe,This image displays: A large rusty pipe with ...,True,3
3,https://filmfare.wwmindia.com/content/2017/jul...,MARCH 2009 ''It's sad that a boy and girl can ...,This image displays: three pictures of Katrin...,True,4
4,https://southernersays.com/wp-content/uploads/...,Humpback Whale tail in the Bay of Banderas,This image displays:\nA photograph of a whale...,True,5
...,...,...,...,...,...
2995,https://pix.avax.news/avaxnews/7c/87/0001877c_...,"CGAP Photo Contest -- Maize Grinding, Uganda. ...",This image displays: a young boy using a mach...,True,2996
2996,https://candidegardening.com/img/c8aa3b54-ee4a...,A close up of an Alocasia amazonica plant,This image displays:\n\nAn Alocasia Zebrina p...,True,2997
2997,https://blueridgemountainlife.com/wp-content/u...,Mehaffey Tree Farm after a snow.,This image displays:\n\nThis image displays s...,True,2998
2998,https://www.littledayout.com/wp-content/upload...,Go-karting In Singapore: Off To The Races,This image displays:\n\nThis image displays a...,True,2999
2999,https://cdn0.weddingwire.com/reviews/photos/3/...,The wedding of <PERSON> and Charlie Kaine Phot...,This image displays: A married couple is sitt...,True,3000

In [8]:
filtered_df = filtered_df.set_index(filtered_df["id"])

In [9]:
filtered_df = filtered_df.drop("id", axis=1)

In [10]:
filtered_df

,url,original_caption,vlm_caption,is_downloaded
id,,,,
1,https://media.gettyimages.com/photos/plate-of-...,A plate of food from Murray Bros Caddy Shack a...,This image displays: A plate of fried calamar...,True
2,https://thumbs.dreamstime.com/b/car-riding-wet...,Car riding on wet street. Car driving on wet c...,This image displays:\n\nA black car driving t...,True
3,https://images.pexels.com/photos/770224/pexels...,Water Coming Out Of A Pipe,This image displays: A large rusty pipe with ...,True
4,https://filmfare.wwmindia.com/content/2017/jul...,MARCH 2009 ''It's sad that a boy and girl can ...,This image displays: three pictures of Katrin...,True
5,https://southernersays.com/wp-content/uploads/...,Humpback Whale tail in the Bay of Banderas,This image displays:\nA photograph of a whale...,True
...,...,...,...,...
2996,https://pix.avax.news/avaxnews/7c/87/0001877c_...,"CGAP Photo Contest -- Maize Grinding, Uganda. ...",This image displays: a young boy using a mach...,True
2997,https://candidegardening.com/img/c8aa3b54-ee4a...,A close up of an Alocasia amazonica plant,This image displays:\n\nAn Alocasia Zebrina p...,True
2998,https://blueridgemountainlife.com/wp-content/u...,Mehaffey Tree Farm after a snow.,This image displays:\n\nThis image displays s...,True
2999,https://www.littledayout.com/wp-content/upload...,Go-karting In Singapore: Off To The Races,This image displays:\n\nThis image displays a...,True
3000,https://cdn0.weddingwire.com/reviews/photos/3/...,The wedding of <PERSON> and Charlie Kaine Phot...,This image displays: A married couple is sitt...,True

In [11]:
filtered_df.loc[1]

url                 https://media.gettyimages.com/photos/plate-of-...
original_caption    A plate of food from Murray Bros Caddy Shack a...
vlm_caption          This image displays: A plate of fried calamar...
is_downloaded                                                    True
Name: 1, dtype: object

In [12]:
failed_extractions, new_df = read_images(filtered_df, "./images")

['https://media.gettyimages.com/photos/plate-of-food-from-murray-bros-caddy-shack-at-the-world-golf-hall-of-picture-id916117812?s=612x612', 'https://thumbs.dreamstime.com/b/car-riding-wet-street-driving-city-downpour-60931822.jpg', 'https://images.pexels.com/photos/770224/pexels-photo-770224.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260', 'https://filmfare.wwmindia.com/content/2017/jul/thu_1_1500193447.jpg', 'https://southernersays.com/wp-content/uploads/2018/04/Whale5-1024x662.jpg', 'https://i.pinimg.com/originals/9a/f5/a6/9af5a623e24e12e436dd58ca61f2d5d9.jpg', 'https://themaydan.com/wp-content/uploads/2019/04/Muslim-Idenitity.jpg', 'https://i.pinimg.com/originals/ae/f4/f3/aef4f34a16c78727fbffcc77597e15f3.jpg', 'https://photogallery.indiatimes.com/photo/65515678.cms', 'https://images.squarespace-cdn.com/content/v1/54611cb7e4b01809e28916e6/1499549254199-XJDTJVPLG5AAY5YE7T3F/ke17ZwdGBToddI8pDm48kG87Sfbgg29A4BYEDq3OXvgUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcf4OxbJOyh_wHUnyc4kQLQ6SBshRGOku7c30Y_IRDNPta8R2IY5BHMaEj1zOWoDTZ/split+croatia', 'https://slideplayer.com/slide/13821916/85/images/27/The+Development+of+the+Court.jpg', 'https://www.theperspective.com/wp-content/uploads/2019/08/sean-pollock-PhYq704ffdA-unsplash-433x420.jpg', 'https://images.squarespace-cdn.com/content/v1/57c45d0a4402435fb533fd94/1512582396048-BWW528MJ7G76063I3TSW/ke17ZwdGBToddI8pDm48kPPQX-pNGR9lbIU0Y04L1GJ7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QHyNOqBUUEtDDsRWrJLTmxyXvWKJWcy4t4TJMVJdPeka3nWit-MF9sAUQD6OtCv4S0kfDtyYxUVwcnjUVCWIu/IMG_1681.JPG?format=1000w', 'https://s.hdnux.com/photos/22/77/21/4977788/3/920x920.jpg', 'https://static.spotapps.co/spots/b3/140e75876945869766397af0b26b79/full', 'https://a.1stdibscdn.com/early-19th-century-masons-ironstone-dinner-plate-in-chinese-scroll-pattern-for-sale-picture-2/f_9903/f_119109431535732024819/IMG_2486_master.JPG?width=768', 'https://thumbs.dreamstime.com/b/waving-flag-made-symbols-computer-screen-vietnam-text-conceptual-d-rendering-123590227.jpg', 'https://images.squarespace-cdn.com/content/v1/55e9da69e4b0dd6c36dfa959/1483472772493-QYMGTBBN5XO7KEAW9FK4/ke17ZwdGBToddI8pDm48kG4sWXxm5MLGzYXxhI3Emb8UqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcDFrDsapgIo0q8jUcW8rNPjhtZThjXNYUQzTwr7Xuxi1NR1RJqyZivqtN160e7oMj/unspecified-13.jpg', 'https://images.squarespace-cdn.com/content/v1/550b4541e4b0acb1af8c895f/1482110846288-R5QSCDYH1W64SFT7Y0DN/ke17ZwdGBToddI8pDm48kFh1G1vCIJq0HQG_--6AOjN7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1UbkWs11vZqY4A4_shNKbeo7Q8a8p8WNXd1QdIPcQVzkwZi9ON07G6OunhMTYtjQPiQ/Fireplace.jpg', 'https://i.pinimg.com/originals/c3/d3/cc/c3d3ccc76bd0619d1741de0682267d26.jpg', 'https://wallpapercave.com/wp/wp4839342.jpg', 'https://image.shutterstock.com/image-vector/no-jump-sign-vector-design-600w-615224387.jpg', 'https://i.pinimg.com/originals/1c/2c/f7/1c2cf74cc61acc65c1687d8e15c4a9ff.jpg', 'https://s.hdnux.com/photos/01/10/46/61/19033199/3/920x920.jpg', 'https://images.squarespace-cdn.com/content/v1/58b35c11cd0f681d20c834db/1552350616825-EH4HKLCKHXHQPTLLTW0U/ke17ZwdGBToddI8pDm48kG6DEqWFQGN86Yy_kIwYHV57gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QHyNOqBUUEtDDsRWrJLTmQPoRzxSr1hzN-vPBHt7YyK04k3j-IK39m3MLCy1OWzJvtn8WJ5C3AsqSwDQDxoEq/A7_08505.jpeg', 'https://i.pinimg.com/originals/5a/4e/82/5a4e82b093456e7fa42a0669c8042f08.jpg', 'https://as1.ftcdn.net/jpg/02/46/17/76/500_F_246177679_6nEqcIlsUgXwQsbxaJHeQJsLuscFxcYu.jpg', 'http://cdn.jordanspieth.psdops.com/dims4/default/1fc5d3b/2147483647/resize/1590x894/quality/90/?url=http%3A%2F%2Fcdn.jordanspieth.psdops.com%2Fcb%2Fe3%2Ff0a863464a9ba79ee9f9cd8f9bb6%2F2018-genesis-open-round-1-jordan-and-kevin-chappell-walk-to-the-ninth-hole.jpg', 'https://bermudarover.files.wordpress.com/2014/07/img_9688.jpg?w=940&h=977', 'https://images.trvl-media.com/hotels/1000000/30000/22300/22295/3c5df612_z.jpg', 'https://i.pinimg.com/originals/4b/34/50/4b3450259620611caf935f503563955f.jpg', 'https://cdn.pixabay.com/photo/2017/10/27/23/41/the-horse-2895858_960_720.jpg', 'https://media-cdn.tripadvisor.com/media/photo-s/01/11/ea/56/old-furniture-and-tv.jpg', 'http://www.paintinghere.com/UploadPic/Thomas%20Cole/big/The%20Garden%20of%20Eden.jpg', 'https://lid.zoocdn.com/645/430/f02eb6835b8ac5ef10b170fdb272a27665320263.jpg', 'https://media-cdn.tripadvisor.com/media/photo-s/0a/a8/c1/b5/mercedes-gull-wing.jpg', 'https://thumbs.dreamstime.com/b/pumpkin-zombie-hand-pumpkin-zombie-hand-halloween-season-vector-162542194.jpg', 'https://static1.businessinsider.com/image/53c690736da81104448d728b-1190-625/the-27-maps-that-explain-america.jpg', 'https://www.parks.ox.ac.uk/sites/default/files/styles/listing_tile_text_displayed_image/public/parks/images/article/vs_oxford-6586.jpg?itok=wyf2kNZC', 'https://image.shutterstock.com/z/stock-vector-gold-lettering-happy-birthday-on-a-dark-background-532027657.jpg', 'https://i.pinimg.com/originals/fc/d5/2f/fcd52f9f4bcd64d2cbbe8910b5d2658a.jpg', 'https://flashbak.com/wp-content/uploads/2015/12/New-York-Street-Scenes-1950s-5.jpg', 'https://media.self.com/photos/5cc1a10a98005a21869421a7/master/w_400%2Cc_limit/Spicy-Chunky-Tuna-Sandwich-12.jpg', 'https://slmarket.com/wp-content/uploads/2015/11/Mercedes-280SL-Buds-Benz-Gooding-Auction-Sale-900x500.jpg', 'https://cdn.vox-cdn.com/thumbor/V1LF97UnXN9ZB7eF90rv5dVn9-c=/0x0:3960x2848/1200x800/filters:focal(1664x1108:2296x1740)/cdn.vox-cdn.com/uploads/chorus_image/image/65320947/_88A5933_4Balanced.0.jpg', 'https://c4.wallpaperflare.com/wallpaper/679/848/1020/girl-the-sun-figure-shorts-wallpaper-preview.jpg', 'https://a.1stdibscdn.com/italian-bronze-tuscany-neoclassical-style-sculpture-featuring-a-relaxed-woman-for-sale-picture-8/f_17262/1549918366993/IMG_2855_master.JPG?width=768', 'https://thumbs.dreamstime.com/b/hand-throwing-green-frisbee-disc-park-summer-day-117073707.jpg', 'https://www.destinationsdetoursdreams.com/wp-content/uploads/2017/05/royal-bc-museum-discovery.jpg', 'https://pix10.agoda.net/hotelImages/346/346078/346078_1212090114009201027.jpg?s=1024x768', 'https://debtcamel.co.uk/wp-content/uploads/2018/12/pensions-dont-delay.jpg', 'https://i.pinimg.com/originals/70/be/2d/70be2dfb1840154056857cee306a6bb3.jpg', 'https://i.ytimg.com/vi/yzBT_gR_jQw/maxresdefault.jpg', 'https://images.immediate.co.uk/production/volatile/sites/21/2019/03/shimano_climbers_jersey-1504026846543-a8oupqkwsjhl-d5460bf.jpg?quality=90&resize=960%2C540', 'https://d23iiv8m8qvdxi.cloudfront.net/wp-content/uploads/2016/11/8339-0-885x589.jpg', 'https://r-cf.bstatic.com/images/hotel/max1024x768/237/23734096.jpg', 'https://media.defense.gov/2008/Apr/25/169361/750/422/0/080425-M-8012P-004.jpg', 'https://thumbs.dreamstime.com/b/flat-colored-isolated-striped-ice-cream-sprinkled-glaze-blue-color-wooden-stick-little-pink-butterfly-simple-drawing-166450377.jpg', 'https://adlamtransport.b-cdn.net/wp-content/uploads/2016/08/quicklypackyourhome.jpg', 'https://thumbs.dreamstime.com/b/man-office-suit-meditating-under-glass-dome-people-running-around-panicking-self-quarantine-stay-home-concept-flat-man-178649775.jpg', 'https://scx1.b-cdn.net/csz/news/800/2020/astretchable.jpg', 'https://media.defense.gov/2020/Jan/03/2002230466/780/780/0/191115-N-KC128-034.JPG', 'https://media-cdn.tripadvisor.com/media/photo-s/12/31/b4/f3/waiting-a-train-at-groombridge.jpg', 'https://images.slideplayer.com/24/7068145/slides/slide_60.jpg', 'https://buckleofficial.files.wordpress.com/2017/05/3u6a7920.jpg?w=750', 'https://media-cdn.tripadvisor.com/media/photo-s/13/0e/ab/a2/we-carry-a-wide-array.jpg', 'https://i.pinimg.com/originals/84/0f/c7/840fc7d4ca3828605d91eafc3d21c07f.jpg', 'https://c1.wallpaperflare.com/preview/918/709/118/technology-business-phone-technology.jpg', 'https://cdn.arstechnica.net/wp-content/uploads/2019/12/GettyImages-1130598362-800x486.jpg', 'https://cdn.shopify.com/s/files/1/2204/5473/files/HouseReef_1000x_3x_f0664b41-49d5-4894-b65c-637748e45e2b_1000x@3x.jpg?v=1536562385', 'https://media.gettyimages.com/photos/young-girl-buried-in-beach-sand-having-cold-drink-with-a-straw-during-picture-id466703775?s=612x612', 'https://farm6.staticflickr.com/5512/10891256504_116eef8f6b_c.jpg', 'http://www.vgdesigner.net/_include/img/work/thumbs/image-20.jpg', 'https://thumbs.dreamstime.com/b/gray-british-cat-sitting-bluish-rug-149317914.jpg', 'https://media.gettyimages.com/photos/ren-goscinny-and-albert-uderzo-drawing-during-the-recording-of-the-picture-id600206811?s=612x612', 'https://media-cdn.tripadvisor.com/media/photo-s/03/e8/4d/53/westin-resort-spa-puerto.jpg', 'https://thumbs.dreamstime.com/b/gradient-shaded-cartoon-globe-world-creative-illustrated-149289721.jpg', 'https://cdn.shopify.com/s/files/1/0246/7663/0627/products/product-image-879606030_f89cedf5-373a-4a75-a693-ee14dec8b2c4_2000x.jpg?v=1572230572', 'https://alchetron.com/cdn/The-Company-Men-images-f2032955-6803-4819-9d20-4567600d028.jpg', 'https://gettingontravel.com/wp-content/uploads/2018/11/IMG_7273.jpg', 'http://www.visitingnewengland.com/PageMill_Resources/classic-new-england-architecture.jpg', 'https://images.trvl-media.com/hotels/30000000/29510000/29504000/29503935/7b081477_z.jpg', 'https://buzzsharer.com/wp-content/uploads/2015/07/American-Warmblood.jpg', 'https://static1.squarespace.com/static/57c9dea8725e251e1ccedb72/57d0d5ae893fc0e4561ebdaf/5c4b85620e2e729185ec7b24/1586469659271/20190119_171259.jpg?format=2500w', 'https://static1.squarespace.com/static/548f24c2e4b0609ef41c747b/55942c6ee4b0c9c17ebf81b7/5dfb689094039d2f6da8b4e5/1587238427221/A+Day+at+the+Beach.jpg?format=1000w', 'https://cdn1.i-scmp.com/sites/default/files/styles/768x768/public/images/methode/2016/09/10/d676d3e6-7707-11e6-800a-ae97f003174d_1280x720.JPG?itok=oBnJyqE5', 'https://lovefashiontee.s3.us-east-2.amazonaws.com/Every-snack-you-make-every-meal-you-bake-Shirt', 'https://i.pinimg.com/originals/a2/52/09/a25209a5eec8baa44e7db4963e6a4176.jpg', 'https://www.ofdesign.net/wp-content/uploads/files/4/1/3/arrange-flowers-like-a-pro-dandelion-ranch-floral-arrangements-4-413.jpeg', 'http://www.whitesellgroup.com/wp-content/uploads/2016/02/Whitesell-Quality-Systems-Escalation-Process-image.jpg', 'https://thumbs.dreamstime.com/b/writing-note-showing-be-light-business-photo-showcasing-enlighten-other-showing-your-attitude-be-optimistic-writing-note-140253757.jpg', 'https://image.shutterstock.com/z/stock-photo-hydrangea-macrophylla-hortensia-flower-beautiful-bush-of-hydrangea-flowers-in-a-garden-1136726597.jpg', 'https://thumbs.dreamstime.com/b/rooms-blue-sofa-built-wardrobe-wooden-floor-home-91460782.jpg', 'https://res.cloudinary.com/scalefunder/image/fetch/s--MIeb8I26--/f_auto,fl_lossy,h_1442,q_auto,w_3383/http://i.imgur.com/Vgamzjv.jpg', 'https://www.andrewswalks.co.uk/wp-content/gallery/appleby/Appleby-40.jpg', 'https://thumbs.dreamstime.com/b/lino-printed-background-texture-scanned-lino-print-colorized-mid-light-blue-lino-printed-texture-graduated-117892857.jpg', 'https://cdn3.vectorstock.com/i/1000x1000/98/67/fruits-alphabet-a-is-for-apricot-fruits-vector-21429867.jpg', 'https://a.1stdibscdn.com/archivesE/upload/f_10470/f_64951631485523461251/Spaghetti_Chair_G_Belotti_for_Alias_1700_l.jpg', 'https://www.wed2b.co.uk/wp/wp-content/uploads/2019/08/Banner-2.jpg', 'https://thumbs.dreamstime.com/b/grungy-worn-hazard-stripes-texture-eps-8-23324787.jpg', 'https://i.chzbgr.com/full/4006661/hC4577BDB/people-on-twitter-are-hilariously-confused-by-this-coffee-riddle', 'https://www.adtob.com/uploads/2018/10/ad-ma-jpg-m0yz.jpg', 'https://i.pinimg.com/originals/f0/d3/cc/f0d3cc39f8aa983527cbac896f444e6b.jpg', 'https://charlotteelizabethphotography.com/wp-content/uploads/2019/04/Laura-Andrew-691.jpg', 'https://images.squarespace-cdn.com/content/v1/5265932fe4b0982ce1891975/1463433718994-QFP9HO75RQN5B6I934ZT/ke17ZwdGBToddI8pDm48kJUlZr2Ql5GtSKWrQpjur5t7gQa3H78H3Y0txjaiv_0fCm2jZnKwyJSlb-AlLxnEdUwqN9guzOIbFq00lUwhe0PwLv1ylhc9WxeIva5tjENnOqpeNLcJ80NK65_fV7S1UZPw7yXH013jDpvRNSKlsMqEFuT_vZIy4TO7gMf4wwAHNKEu28rD9AFzTNbT_UZh4Q/upload.jpeg?format=1000w', 'https://www.mistilayne.com/wp-content/uploads/2017/11/Palace-Proposal-Misti-Layne_144-682x1024.jpg', 'https://thumbs.dreamstime.com/b/vector-paper-cut-illustration-cosmos-black-hole-vector-paper-cut-illustration-black-hole-cosmos-117970003.jpg', 'https://carsguide-res.cloudinary.com/image/upload/f_auto,fl_lossy,q_auto,t_cg_hero_large/v1/editorial/dp/albums/album-730/lg/800px-Austin_Healey_Sprite_frogeye_x_2.jpg', 'https://scienceline.org/wp-content/uploads/2019/12/Sleep.Photo_.jpg', 'https://d36tnp772eyphs.cloudfront.net/blogs/1/2019/10/Variety-of-hand-made-swiss-chocolate-1200x853.jpg', 'https://ae01.alicdn.com/kf/HTB12elCbyrxK1RkHFCcq6AQCVXac/Periodic-Table-of-The-Elements-Chart-Chemical-Science-Poster-Prints-Wall-Art-Painting-Wall-Pictures-For.jpg', 'https://media.bloomsbury.com/rep/bj/9781350093836.jpg', 'https://www.justwhitevillas.com/wp-content/uploads/2017/02/villa-sotavento-slide01.jpg', 'https://www.thecartoonpictures.com/data/media/138/Barbie_in_The_Pink_Shoes_Kristyn_Farraday_Small_Doll.jpg', 'https://media.gettyimages.com/photos/sofia-wellesley-and-james-blunt-attend-the-uk-premiere-of-rocketman-picture-id1145307916?s=612x612', 'https://n.nordstrommedia.com/id/2cd8d558-93b4-48ea-ae53-c86fbf28c781.jpeg?h=799&w=670', 'http://theweddingplaybook.com/wp-content/uploads/Blue-and-White-DIY-Country-Wedding-Reception.jpg', 'https://images.axios.com/exKlaKmVyWOtLLFgnY5Gj_NENm8=/2020/04/05/1586055981223.jpg', 'https://static2.tripoto.com/media/filter/tst/img/21119/TripDocument/img_5004.jpg', 'https://r-cf.bstatic.com/images/hotel/max1024x768/678/67801351.jpg', 'https://cdn.dealerspike.com/imglib/v1/800x600/imglib/trimsdb/11551781-0-89533621.jpg', 'https://chairish-prod.freetls.fastly.net/image/product/sized/08e8bc3a-817c-482b-8615-0294f5c220b9/1968-vintage-emile-gruppe-woman-on-a-beach-painting-0461?aspect=fit&width=640&height=640', 'http://numismaclub.com/imgs/a/e/t/v/w/1934_a_20_dollar_bill_star_federal_reserve_note_old_paper_money_2_lgw.jpg', 'http://img.koreatimes.co.kr/upload/newsV2/images/201901/016153d1cd844ef6b502156911dcf308.jpg/dims/resize/740/optimize', 'https://www.south-african-hotels.com/media/crowne-plaza-johannesburg-the-rosebank-5.jpg', 'https://images.squarespace-cdn.com/content/v1/5449a23fe4b04f35b928c028/1458182303817-296WDQAQFTZWQ44O4ZZH/ke17ZwdGBToddI8pDm48kM1TFzP2I5SJH8Y-tipXrjF7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1UUcpJaSVLp_UslIuGuwBanA2pasV9Ckn0p5B8MMfqc1eISvQmwN60hB-jM3cH1Ew2w/IMG_0007_crop.jpg', 'https://www.picclickimg.com/d/l400/pict/323867813166_/All-African-Styles-Tops-Embroidery-Traditional-Dress-For.jpg', 'https://ak1.ostkcdn.com/images/products/is/images/direct/300cd3e8f6e3edbd868064691218e39e5e89d056/Premium-Thick-Wrap-Canvas-entitled-Close-up-of-a-paint-tube-and-brushes.jpg?impolicy=medium', 'https://image.shutterstock.com/image-photo/shaggy-matted-hair-dog-sitting-600w-759072163.jpg', 'https://veggiedesserts.com/wp-content/uploads/2017/06/Vegan-vanilla-cake-2.jpg', 'https://images.slideplayer.com/12/3551677/slides/slide_1.jpg', 'https://theladybirdsadventures.co.uk/wp-content/uploads/2017/07/IMG_3528.jpg', 'https://media.gettyimages.com/photos/the-logo-of-music-streaming-platform-spotify-is-displayed-on-a-on-picture-id1074311240?s=612x612', 'https://s3.eu-west-2.amazonaws.com/online24-production/listings/nk7hc/photos/taj-5-gp.jpg', 'https://i.pinimg.com/originals/4d/51/4d/4d514dafcab1439b13fb86836cc1481c.jpg', 'http://www.bangkok-housing.com/condo-id/bh1184.jpg', 'https://i.pinimg.com/originals/10/04/38/10043838ac0633df5bb9b7b80bd9292b.jpg', 'https://i.pinimg.com/originals/15/e4/1f/15e41fcfe9f3126e95c585e14664e122.jpg', 'https://media.gettyimages.com/photos/player-klay-thompson-of-the-golden-state-warriors-as-a-goalkeeper-he-picture-id983904808?s=612x612', 'https://cdn.shopify.com/s/files/1/2208/7997/products/IMG_9473-2_500x500.jpg?v=1584110897', 'https://media.defense.gov/2018/Jul/26/2001947038/780/780/0/180724-F-GA541-0406.JPG', 'https://i.pinimg.com/originals/c5/93/7c/c5937c53cffd14fd53509bda37c93c10.jpg', 'http://www.mizzima.com/sites/default/files/styles/news_category_large_image/public/news-images/poor-slums-in-yangon.jpg?itok=iB9_xhbv', 'https://images.squarespace-cdn.com/content/v1/54a15effe4b0510339b6e5db/1466522256843-H0AFVHBHSJUV91DSKAE8/ke17ZwdGBToddI8pDm48kD33KhhWEodMJvcytjXFyvFZw-zPPgdn4jUwVcJE1ZvWgCjmTad1QpYCGph9EV4QZamWLI2zvYWH8K3-s_4yszcp2ryTI0HqTOaaUohrI8PISUdMARDvQJRl4fGnVdl7d0Wycykif_4SkMazoCPJbvMKMshLAGzx4R3EDFOm1kBS/Walden+-+Hygienic+Dress+League+-+Port+Austin%2C+MI?format=1000w', 'https://cdn1.thegraciouswife.com/wp-content/uploads/2016/03/Read2Me-Ways-to-Help-Kids-Fall-Asleep-6.jpg', 'https://www.westallrealestate.com/wp-content/uploads/2016/02/TSIERRA20140880-1024x681.jpg', 'https://i.pinimg.com/originals/69/c8/2d/69c82db90b57a94b6350c13088da31b3.jpg', 'https://i.pinimg.com/originals/f9/49/cf/f949cf6d644f38e76b89941579b56802.jpg', 'https://images.squarespace-cdn.com/content/v1/55b29de4e4b088f33db802c6/1568393690368-9R1RKDJHLV3E6VRA68EC/ke17ZwdGBToddI8pDm48kA0wePVlgOGM5yNNrADThjYUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKc3f5rMIUspMOT17T3MGHdS3s1KwpjdUupKJDR9JNb8i8O932tY93Uq43o4DcCmt6U/IMG_20180520_124912.jpg?format=750w', 'https://thumbs.dreamstime.com/b/sleeping-fox-put-muzzle-tail-one-curled-up-asleep-his-head-53100880.jpg', 'https://i.pinimg.com/originals/0e/95/14/0e9514d1f758643c3090ecea225e2ad1.jpg', 'https://gardenhomeandparty.files.wordpress.com/2015/04/a-nantucket-state-of-mind.jpg?w=529', 'https://www.coolcattreeplans.com/wp-content/uploads/2019/12/The-Best-Tall-Cat-Tree-For-Large-Cats-In-2020-F-4.jpg', 'https://static1.bigstockphoto.com/4/5/6/large2/65493973.jpg', 'https://ih1.redbubble.net/image.554091419.6689/poster,840x830,f8f8f8-pad,1000x1000,f8f8f8.u2.jpg', 'https://thumbs.dreamstime.com/b/pregnant-woman-standing-window-beautiful-azure-dre-pregnant-woman-standing-window-beautiful-azure-101635483.jpg', 'https://colomusic.org/wp-content/uploads/2020/04/the-young-rascals-poster-1967.jpg', 'https://slideplayer.com/slide/7340119/24/images/15/Special+text+The+purpose+of+using+special+text+such+as+italics+or+bold+is+to.+A%29+To+make+the+text+attractive+and+easy+to+read..jpg', 'https://d3nevzfk7ii3be.cloudfront.net/igi/OLMmpxVQvvf5nxKV.medium', 'https://daddytee.com/wp-content/uploads/Pikachu-link-the-legend-of-Zelda-shirt-1000x1000.jpg', 'https://i.pinimg.com/originals/f3/45/4b/f3454bbd39074f9b3b278b3acd6cf052.jpg', 'https://www.pavexparquet.com/en/imag/medalions/MQM3-Compass-III-owass-hardwood-floor-medallion.jpg', 'https://images.bayut.com/thumbnails/86464430-400x300.jpeg', 'https://imgc.artprintimages.com/img/print/strike-up-the-band-judy-garland-1940_u-l-ph5ogl0.jpg?LID=55&h=550&w=550&background=fbfbfb', 'https://images.squarespace-cdn.com/content/v1/5b3b4bc7e2ccd1efc95ca108/1563425185561-CGY18V5XCBLYYH7M0STT/ke17ZwdGBToddI8pDm48kGTJ8Z1cmxTlWoEgYHtRFB0UqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8PaoYXhp6HxIwZIk7-Mi3Tsic-L2IOPH3Dwrhl-Ne3Z2CmM36Zl4gtM3rrckeQVk7d1wHpBH1aG7pbxzWwyEUnwm_AaHWq01a8yFgqe9oqFs/Kinghts+Point+Sea+Stacks+-+New+Zealand.jpg', 'https://plantcaretoday.com/wp-content/uploads/foxglove-plant-08312016.jpg', 'https://farm4.static.flickr.com/3239/3021512867_8d86c1cd23.jpg', 'https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fblogs-images.forbes.com%2Fforbestravelguide%2Ffiles%2F2018%2F08%2FFORBES-YourVictoriaFoodieGuide-MagnoliaHotel-CreditMagnoliaHotel.jpg', 'https://i.pinimg.com/originals/91/28/9a/91289ae8946d5e3ec23e833242afbd4e.jpg', 'https://i.pinimg.com/originals/35/a4/25/35a4257c605b29f1cde6bc6fdaede0f7.jpg', 'https://api.time.com/wp-content/uploads/2018/11/living-with-the-gods-the-virgin-mary.jpg?w=600&quality=85', 'https://www.nps.gov/peco/learn/historyculture/images/church-view-by-suzan-schaaf-sm.jpg?maxwidth=1200&maxheight=120

In [13]:
len(failed_extractions)

587

In [14]:
new_df

,url,original_caption,vlm_caption,is_downloaded
id,,,,
1,https://media.gettyimages.com/photos/plate-of-...,A plate of food from Murray Bros Caddy Shack a...,This image displays: A plate of fried calamar...,False
2,https://thumbs.dreamstime.com/b/car-riding-wet...,Car riding on wet street. Car driving on wet c...,This image displays:\n\nA black car driving t...,True
3,https://images.pexels.com/photos/770224/pexels...,Water Coming Out Of A Pipe,This image displays: A large rusty pipe with ...,True
4,https://filmfare.wwmindia.com/content/2017/jul...,MARCH 2009 ''It's sad that a boy and girl can ...,This image displays: three pictures of Katrin...,True
5,https://southernersays.com/wp-content/uploads/...,Humpback Whale tail in the Bay of Banderas,This image displays:\nA photograph of a whale...,True
...,...,...,...,...
2996,https://pix.avax.news/avaxnews/7c/87/0001877c_...,"CGAP Photo Contest -- Maize Grinding, Uganda. ...",This image displays: a young boy using a mach...,True
2997,https://candidegardening.com/img/c8aa3b54-ee4a...,A close up of an Alocasia amazonica plant,This image displays:\n\nAn Alocasia Zebrina p...,False
2998,https://blueridgemountainlife.com/wp-content/u...,Mehaffey Tree Farm after a snow.,This image displays:\n\nThis image displays s...,True
2999,https://www.littledayout.com/wp-content/upload...,Go-karting In Singapore: Off To The Races,This image displays:\n\nThis image displays a...,True
3000,https://cdn0.weddingwire.com/reviews/photos/3/...,The wedding of <PERSON> and Charlie Kaine Phot...,This image displays: A married couple is sitt...,False

In [33]:
# clean csv before saving
df_to_save = new_df[new_df["is_downloaded"] == True]
# change ids

In [34]:
df_to_save

,url,original_caption,vlm_caption,is_downloaded
id,,,,
2,https://thumbs.dreamstime.com/b/car-riding-wet...,Car riding on wet street. Car driving on wet c...,This image displays:\n\nA black car driving t...,True
3,https://images.pexels.com/photos/770224/pexels...,Water Coming Out Of A Pipe,This image displays: A large rusty pipe with ...,True
4,https://filmfare.wwmindia.com/content/2017/jul...,MARCH 2009 ''It's sad that a boy and girl can ...,This image displays: three pictures of Katrin...,True
5,https://southernersays.com/wp-content/uploads/...,Humpback Whale tail in the Bay of Banderas,This image displays:\nA photograph of a whale...,True
6,https://i.pinimg.com/originals/9a/f5/a6/9af5a6...,"The gaming Team logo of team DUO Team Logo, My...","This image displays:\n\nText that reads ""20% ...",True
...,...,...,...,...
2994,https://thumbs.dreamstime.com/b/texture-sea-wa...,The texture of sea water and foam. Blue waves....,This image displays: Large greenish-blue wave...,True
2995,https://i.pinimg.com/originals/ed/b8/a2/edb8a2...,The Walking Dead Alexandria Map The Walking De...,"This image displays:\n\nA map of Alexandria, ...",True
2996,https://pix.avax.news/avaxnews/7c/87/0001877c_...,"CGAP Photo Contest -- Maize Grinding, Uganda. ...",This image displays: a young boy using a mach...,True
2998,https://blueridgemountainlife.com/wp-content/u...,Mehaffey Tree Farm after a snow.,This image displays:\n\nThis image displays s...,True
2999,https://www.littledayout.com/wp-content/upload...,Go-karting In Singapore: Off To The Races,This image displays:\n\nThis image displays a...,True

In [35]:
df_to_save

,url,original_caption,vlm_caption,is_downloaded
id,,,,
2,https://thumbs.dreamstime.com/b/car-riding-wet...,Car riding on wet street. Car driving on wet c...,This image displays:\n\nA black car driving t...,True
3,https://images.pexels.com/photos/770224/pexels...,Water Coming Out Of A Pipe,This image displays: A large rusty pipe with ...,True
4,https://filmfare.wwmindia.com/content/2017/jul...,MARCH 2009 ''It's sad that a boy and girl can ...,This image displays: three pictures of Katrin...,True
5,https://southernersays.com/wp-content/uploads/...,Humpback Whale tail in the Bay of Banderas,This image displays:\nA photograph of a whale...,True
6,https://i.pinimg.com/originals/9a/f5/a6/9af5a6...,"The gaming Team logo of team DUO Team Logo, My...","This image displays:\n\nText that reads ""20% ...",True
...,...,...,...,...
2994,https://thumbs.dreamstime.com/b/texture-sea-wa...,The texture of sea water and foam. Blue waves....,This image displays: Large greenish-blue wave...,True
2995,https://i.pinimg.com/originals/ed/b8/a2/edb8a2...,The Walking Dead Alexandria Map The Walking De...,"This image displays:\n\nA map of Alexandria, ...",True
2996,https://pix.avax.news/avaxnews/7c/87/0001877c_...,"CGAP Photo Contest -- Maize Grinding, Uganda. ...",This image displays: a young boy using a mach...,True
2998,https://blueridgemountainlife.com/wp-content/u...,Mehaffey Tree Farm after a snow.,This image displays:\n\nThis image displays s...,True
2999,https://www.littledayout.com/wp-content/upload...,Go-karting In Singapore: Off To The Races,This image displays:\n\nThis image displays a...,True

In [ ]:
# can reset the row ids. 
df_to_save = df_to_save.reset_index()
df_to_save = df_to_save.drop("id", axis=1)
df_to_save.index = range(1, len(df_to_save)+1)
df_to_save["id"] = range(1, len(df_to_save)+1)

In [54]:
# now we change up image paths
folder_path = "./images"
img_nums = [int(re.search(r"img_(\d+)\.jpg", f).group(1)) for f in os.listdir(folder_path)]
img_nums.sort()  # sort to maintain order

In [55]:
img_nums

[1,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 54,
 55,
 58,
 59,
 60,
 61,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 72,
 73,
 74,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 116,
 117,
 118,
 119,
 121,
 122,
 123,
 125,
 126,
 128,
 129,
 130,
 131,
 132,
 134,
 135,
 136,
 137,
 138,
 140,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 154,
 156,
 157,
 158,
 159,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 175,
 176,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 217,
 218,
 219,
 221,
 223,
 224,
 225,
 226,
 228,
 231,
 232,
 233,
 235,
 236,
 237,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 248,
 250,
 251,
 252,
 253,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 265,
 266,
 267,
 268,
 270,
 271,
 273,
 274,
 275,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 293,
 294,
 295,
 296,
 297,
 298,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 310,
 311,
 312,
 313,
 315,
 316,
 317,
 318,
 319,
 321,
 322,
 323,
 324,
 325,
 328,
 329,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 340,
 341,
 342,
 343,
 344,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 373,
 374,
 375,
 376,
 377,
 379,
 380,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 418,
 420,
 421,
 422,
 423,
 424,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 457,
 458,
 460,
 461,
 462,
 463,
 466,
 467,
 468,
 469,
 472,
 473,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 484,
 485,
 489,
 491,
 492,
 493,
 494,
 495,
 497,
 498,
 499,
 500,
 501,
 503,
 504,
 505,
 507,
 508,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 518,
 519,
 520,
 523,
 524,
 525,
 526,
 528,
 529,
 530,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 543,
 544,
 546,
 547,
 548,
 549,
 550,
 551,
 554,
 555,
 556,
 557,
 558,
 560,
 561,
 562,
 563,
 564,
 567,
 568,
 570,
 571,
 572,
 574,
 576,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 586,
 587,
 588,
 589,
 591,
 594,
 595,
 596,
 597,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 608,
 609,
 610,
 611,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 630,
 631,
 632,
 633,
 634,
 636,
 637,
 638,
 639,
 640,
 641,
 644,
 646,
 647,
 648,
 649,
 650,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 660,
 661,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 683,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 720,
 721,
 722,
 725,
 727,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 741,
 742,
 743,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 770,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 791,
 792,
 794,
 795,
 796,
 797,
 798,
 800,
 801,
 802,
 803,
 804,
 805,
 807,
 808,
 810,
 811,
 812,
 813,
 814,
 815,
 817,
 818,
 820,
 821,
 823,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 834,
 835,
 838,
 839,
 840,
 842,
 843,
 844,
 845,
 846,
 849,
 850,
 851,
 855,
 856,
 858,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 872,
 873,
 874,
 876,
 877,
 878,
 881,
 882,
 883,
 884,
 886,
 888,
 889,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 899,
 900,
 901,
 903,
 904,
 906,
 911,
 912,
 914,
 915,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 954,
 955,
 958,
 959,
 960,
 961,
 963,
 964,
 965,
 966,
 968,
 969,
 970,
 971,
 972,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 997,
 998,
 999,
 1000,
 1002,
 1003,
 1005,
 1006,
 1007,
 1008,
 1009,
 1011,
 1012,
 1014,
 1015,
 1017,
 1018,
 1019,
 1020,
 1021,
 1022,
 1023,
 1024,
 1025,
 1027,
 1028,
 1030,
 1032,
 1033,
 1035,
 1036,
 1037,
 1038,
 1039,
 1041,
 1042,
 1043,
 1044,
 1045,
 1046,
 1047,
 1049,
 1051,
 1052,
 1053,
 1054,
 1055,
 1057,
 1058,
 1060,
 1061,
 1062,
 1063,
 1066,
 1067,
 1068,
 1069,
 1070,
 1072,
 1073,
 1074,
 1075,
 1076,
 1078,
 1080,
 1081,
 1082,
 1083,
 1084,
 1085,
 1086,
 1087,
 1088,
 1091,
 1092,
 1093,
 1094,
 1095,
 1096,
 1097,
 1099,
 1100,
 1103,
 1104,
 1105,
 1106,
 1107,
 1108,
 1109,
 1111,
 1112,
 1113,
 1115,
 1116,
 1117,
 1118,
 1119,
 1120,
 1121,
 1122,
 1123,
 1124,
 1125,
 1126,
 1129,
 1130,
 1131,
 1132,
 1133,
 1134,
 1135,
 1137,
 1139,
 1140,
 1141,
 1143,
 1144,
 1145,
 1146,
 1147,
 1148,
 1149,
 1150,
 1152,
 1155,
 1157,
 1159,
 1160,
 1161,
 1162,
 1163,
 1165,
 1166,
 1167,
 1168,
 1169,
 1170,
 1171,
 1172,
 1173,
 1174,
 1175,
 1177,
 1179,
 1182,
 1183,
 1184,
 1185,
 1186,
 1187,
 1188,
 1189,
 1190,
 1191,
 1193,
 1194,
 1195,
 1196,
 1198,
 1199,
 1201,
 1202,
 1203,
 1204,
 1206,
 1207,
 1209,
 1210,
 1211,
 1212,
 1213,
 1214,
 1216,
 1217,
 1218,
 1219,
 1221,
 1222,
 1223,
 1226,
 1227,
 1228,
 1230,
 1231,
 1232,
 1233,
 1234,
 ...]

In [56]:
for idx in range(len(img_nums)):
    img_num_to_rename = img_nums[idx]

    new_name = f"img_{idx+1}.jpg"
    old_name = f"img_{img_num_to_rename}.jpg"

    old_path = os.path.join(folder_path, old_name)
    new_path = os.path.join(folder_path, new_name)
    os.rename(old_path, new_path)